from __future__ import annotations

import gzip
import hashlib
import io
import json
import os
import subprocess
import sys
import tarfile
from contextlib import contextmanager
from pathlib import Path

import jsonschema
import pytest

from scripts.release.build_release_candidate import (
    RETIRED_RELEASE_CONTRACT_PATHS,
    build_release_candidate,
    safe_symlink_target,
)
from scripts.release.check_release_contract import scan
import scripts.release.verify_release_candidate as verifier_module
from scripts.release.verify_release_candidate import verify_release_candidate

ROOT = Path(__file__).resolve().parents[3]
SCHEMA = ROOT / "merger/repoground/contracts/repoground-release-candidate.v1.schema.json"
LICENSE_EXPRESSION = "Apache-2.0"


def _git(repo: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=repo, text=True).strip()


def _minimal_lock() -> str:
    return (
        "# This file is autogenerated by pip-compile with Python 3.12\n"
        "example==1.0.0 \\\n"
        "    --hash=sha256:" + "a" * 64 + "\n"
    )


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.name", "Release Test")
    _git(repo, "config", "user.email", "release@example.invalid")
    (repo / "RELEASE_VERSION").write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "LICENSE").write_text(
        "Apache License\nVersion 2.0, January 2004\n", encoding="utf-8"
    )
    (repo / "NOTICE").write_text("RepoGround\n", encoding="utf-8")
    (repo / "TRADEMARK_POLICY.md").write_text(
        "This policy does not restrict any right granted by Apache-2.0.\n",
        encoding="utf-8",
    )
    (repo / "regular.txt").write_text("regular\n", encoding="utf-8")
    executable = repo / "run.sh"
    executable.write_text("#!/bin/sh\necho ok\n", encoding="utf-8")
    executable.chmod(0o755)
    os.symlink("regular.txt", repo / "link.txt")
    locks = repo / "requirements"
    locks.mkdir()
    for name in ("runtime", "dev", "browser", "lock-tools"):
        (locks / f"repoground-{name}.lock.txt").write_text(
            _minimal_lock(), encoding="utf-8"
        )
    semantic_input = locks / "repoground-semantic-linux-x86_64-py312.in"
    semantic_constraints = (
        locks / "repoground-semantic-linux-x86_64-py312.constraints.txt"
    )
    semantic_lock = locks / "repoground-semantic-linux-x86_64-py312.lock.txt"
    semantic_input.write_text("sentence-transformers==5.6.0\n", encoding="utf-8")
    semantic_constraints.write_text("sentence-transformers==5.6.0\n", encoding="utf-8")
    semantic_lock.write_text(_minimal_lock(), encoding="utf-8")
    semantic_contract = repo / "docs/release/repoground-semantic-platforms.v1.json"
    semantic_contract.parent.mkdir(parents=True)
    semantic_contract.write_text(
        json.dumps({"fixture": "semantic-platform-contract"}) + "\n",
        encoding="utf-8",
    )
    semantic_schema = (
        repo
        / "merger/repoground/contracts/repoground-semantic-platforms.v1.schema.json"
    )
    semantic_schema.parent.mkdir(parents=True)
    semantic_schema.write_text(
        json.dumps({"$schema": "http://json-schema.org/draft-07/schema#", "type": "object"})
        + "\n",
        encoding="utf-8",
    )
    (repo / "merger/repoground/requirements-semantic.txt").write_text(
        "sentence-transformers==5.6.0\n", encoding="utf-8"
    )
    release_scripts = repo / "scripts/release"
    release_scripts.mkdir(parents=True, exist_ok=True)
    (release_scripts / "compile_semantic_lock.py").write_text(
        "# fixture\n", encoding="utf-8"
    )
    (release_scripts / "compile_semantic_lock.sh").write_text(
        "#!/bin/sh\n", encoding="utf-8"
    )
    _git(repo, "add", ".")
    _git(repo, "commit", "-qm", "fixture")
    return repo


def _files(path: Path) -> dict[str, bytes]:
    return {item.name: item.read_bytes() for item in sorted(path.iterdir())}



def _rewrite_sums(candidate: Path) -> None:
    manifest = next(candidate.glob("*.release.json"))
    archive = next(candidate.glob("*.tar.gz"))
    lines = [
        f"{hashlib.sha256(archive.read_bytes()).hexdigest()}  {archive.name}",
        f"{hashlib.sha256(manifest.read_bytes()).hexdigest()}  {manifest.name}",
    ]
    (candidate / "SHA256SUMS").write_text(
        "\n".join(sorted(lines)) + "\n", encoding="utf-8"
    )


def _replace_with_external_symlink(path: Path, tmp_path: Path) -> None:
    target = tmp_path / f"{path.name}.target"
    target.write_bytes(path.read_bytes())
    path.unlink()
    os.symlink(target, path)


def _reverse_archive_members(candidate: Path) -> None:
    archive_path = next(candidate.glob("*.tar.gz"))
    members: list[tuple[tarfile.TarInfo, bytes | None]] = []
    with gzip.open(archive_path, "rb") as gz:
        with tarfile.open(fileobj=gz, mode="r:") as tar:
            for member in tar.getmembers():
                handle = tar.extractfile(member) if member.isfile() else None
                members.append((member, handle.read() if handle is not None else None))
    assert members[0][0].isdir()
    reordered = [members[0], *reversed(members[1:])]
    tar_buffer = io.BytesIO()
    with tarfile.open(fileobj=tar_buffer, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for member, payload in reordered:
            tar.addfile(member, io.BytesIO(payload) if payload is not None else None)
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", fileobj=compressed, compresslevel=9, mtime=0
    ) as gz:
        gz.write(tar_buffer.getvalue())
    archive_path.write_bytes(compressed.getvalue())

    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["archive"]["bytes"] = archive_path.stat().st_size
    manifest["archive"]["sha256"] = hashlib.sha256(
        archive_path.read_bytes()
    ).hexdigest()
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(candidate)


def _rename_archive_member(
    candidate: Path, source_relative: str, target_relative: str
) -> None:
    archive_path = next(candidate.glob("*.tar.gz"))
    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    prefix = manifest["archive"]["prefix"]
    source_name = f"{prefix}{source_relative}"
    target_name = f"{prefix}{target_relative}"

    members: list[tuple[tarfile.TarInfo, bytes | None]] = []
    renamed = False
    with gzip.open(archive_path, "rb") as gz:
        with tarfile.open(fileobj=gz, mode="r:") as tar:
            for member in tar.getmembers():
                handle = tar.extractfile(member) if member.isfile() else None
                payload = handle.read() if handle is not None else None
                if member.name == source_name:
                    member.name = target_name
                    renamed = True
                members.append((member, payload))
    assert renamed

    root_name = prefix.rstrip("/")
    root = next(item for item in members if item[0].name == root_name)
    children = sorted(
        (item for item in members if item[0].name != root_name),
        key=lambda item: item[0].name[len(prefix) :].encode(
            "utf-8", errors="surrogateescape"
        ),
    )
    tar_buffer = io.BytesIO()
    with tarfile.open(fileobj=tar_buffer, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for member, payload in (root, *children):
            tar.addfile(member, io.BytesIO(payload) if payload is not None else None)
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", fileobj=compressed, compresslevel=9, mtime=0
    ) as gz:
        gz.write(tar_buffer.getvalue())
    archive_path.write_bytes(compressed.getvalue())

    manifest["archive"]["bytes"] = archive_path.stat().st_size
    manifest["archive"]["sha256"] = hashlib.sha256(
        archive_path.read_bytes()
    ).hexdigest()
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(candidate)


def _replace_archive_member_payload(
    candidate: Path, target_relative: str, payload: bytes
) -> None:
    archive_path = next(candidate.glob("*.tar.gz"))
    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    prefix = manifest["archive"]["prefix"]
    target_name = f"{prefix}{target_relative}"
    members: list[tuple[tarfile.TarInfo, bytes | None]] = []
    replaced = False
    with tarfile.open(archive_path, mode="r:gz") as tar:
        for member in tar.getmembers():
            handle = tar.extractfile(member) if member.isfile() else None
            content = handle.read() if handle is not None else None
            if member.name == target_name:
                content = payload
                member.size = len(payload)
                replaced = True
            members.append((member, content))
    assert replaced

    tar_buffer = io.BytesIO()
    with tarfile.open(fileobj=tar_buffer, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for member, content in members:
            tar.addfile(member, io.BytesIO(content) if content is not None else None)
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", fileobj=compressed, compresslevel=9, mtime=0
    ) as gz:
        gz.write(tar_buffer.getvalue())
    archive_path.write_bytes(compressed.getvalue())
    manifest["archive"]["bytes"] = archive_path.stat().st_size
    manifest["archive"]["sha256"] = hashlib.sha256(
        archive_path.read_bytes()
    ).hexdigest()
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(candidate)



def _add_global_pax_header(candidate: Path, payload_bytes: int) -> None:
    archive_path = next(candidate.glob("*.tar.gz"))
    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    members: list[tuple[tarfile.TarInfo, bytes | None]] = []
    with tarfile.open(archive_path, mode="r:gz") as tar:
        for member in tar.getmembers():
            handle = tar.extractfile(member) if member.isfile() else None
            members.append((member, handle.read() if handle is not None else None))

    tar_buffer = io.BytesIO()
    with tarfile.open(
        fileobj=tar_buffer,
        mode="w",
        format=tarfile.PAX_FORMAT,
        pax_headers={"comment": "0" * payload_bytes},
    ) as tar:
        for member, content in members:
            tar.addfile(member, io.BytesIO(content) if content is not None else None)
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", fileobj=compressed, compresslevel=9, mtime=0
    ) as gz:
        gz.write(tar_buffer.getvalue())
    archive_path.write_bytes(compressed.getvalue())
    manifest["archive"]["bytes"] = archive_path.stat().st_size
    manifest["archive"]["sha256"] = hashlib.sha256(
        archive_path.read_bytes()
    ).hexdigest()
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(candidate)

def test_candidate_build_is_byte_reproducible_and_source_bound(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    first = tmp_path / "first"
    second = tmp_path / "second"
    result = build_release_candidate(repo, first)
    build_release_candidate(repo, second)
    assert _files(first) == _files(second)
    assert result["distribution_status"] == "permitted_under_project_license"
    self_report = verify_release_candidate(first)
    source_report = verify_release_candidate(first, repo=repo)
    assert self_report["status"] == "pass"
    assert self_report["source_bound"] is False
    assert source_report["source_bound"] is True


def test_candidate_manifest_validates_against_schema(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest = json.loads(next(out.glob("*.release.json")).read_text())
    schema = json.loads(SCHEMA.read_text())
    jsonschema.Draft7Validator(schema).validate(manifest)


def test_candidate_manifest_binds_optional_semantic_surface(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest = json.loads(next(out.glob("*.release.json")).read_text())
    semantic = manifest["semantic_extension"]
    assert semantic["status"] == "optional_locked"
    assert semantic["default_enabled"] is False
    assert semantic["unsupported_target_policy"] == "fail_closed"
    assert semantic["platform_contract"]["path"] == (
        "docs/release/repoground-semantic-platforms.v1.json"
    )
    target = semantic["targets"][0]
    assert target["id"] == "cpython-312-linux-x86_64"
    assert target["lock"]["path"] == (
        "requirements/repoground-semantic-linux-x86_64-py312.lock.txt"
    )


def test_candidate_semantic_lock_claim_must_match_archive(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest_path = next(out.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["semantic_extension"]["targets"][0]["lock"]["sha256"] = "0" * 64
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(out)
    with pytest.raises(ValueError, match="semantic extension SHA-256 mismatch"):
        verify_release_candidate(out)


def test_candidate_tampering_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    result = build_release_candidate(repo, out)
    archive = Path(result["archive"])
    archive.write_bytes(archive.read_bytes() + b"tampered")
    with pytest.raises(ValueError, match="SHA256SUMS"):
        verify_release_candidate(out)




def test_noncanonical_archive_member_order_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    _reverse_archive_members(out)
    with pytest.raises(ValueError, match="archive member order is not canonical"):
        verify_release_candidate(out, repo=repo)


def test_manifest_lock_claim_must_match_archived_lock(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest_path = next(out.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["dependency_locks"][0]["sha256"] = "0" * 64
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    _rewrite_sums(out)
    with pytest.raises(ValueError, match="dependency lock SHA-256 mismatch"):
        verify_release_candidate(out)

def test_dirty_repository_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    (repo / "regular.txt").write_text("dirty\n", encoding="utf-8")
    with pytest.raises(ValueError, match="clean working tree"):
        build_release_candidate(repo, tmp_path / "candidate")



def test_nonempty_output_directory_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    out.mkdir()
    (out / "stale.txt").write_text("stale\n", encoding="utf-8")
    with pytest.raises(ValueError, match="must be empty"):
        build_release_candidate(repo, out)


def test_extra_candidate_file_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    (out / "unexpected.txt").write_text("unexpected\n", encoding="utf-8")
    with pytest.raises(ValueError, match="file set mismatch"):
        verify_release_candidate(out)


def test_symlink_target_must_remain_inside_archive(tmp_path: Path) -> None:
    assert safe_symlink_target("nested/link", "../regular.txt")
    assert not safe_symlink_target("link", "../outside.txt")
    assert not safe_symlink_target("nested/link", "/etc/passwd")

    repo = _repo(tmp_path)
    os.symlink("../../outside.txt", repo / "nested-escape")
    _git(repo, "add", "nested-escape")
    _git(repo, "commit", "-qm", "unsafe symlink")
    with pytest.raises(ValueError, match="unsafe symlink target"):
        build_release_candidate(repo, tmp_path / "candidate")


def test_repository_release_contract_is_consistent() -> None:
    report = scan(ROOT)
    assert report["status"] == "pass", report["findings"]


def test_release_contract_gate_runs_without_site_packages() -> None:
    result = subprocess.run(
        [sys.executable, "-S", "scripts/release/check_release_contract.py"],
        cwd=ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    assert result.returncode == 0, result.stderr or result.stdout
    assert json.loads(result.stdout)["status"] == "pass"


def test_release_contract_rejects_unhashed_lock(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    # Supply the remaining policy files so the lock finding is isolated.
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "requirements/repoground-runtime.lock.txt").write_text(
        "# Python 3.12\nexample==1.0.0 \\\n", encoding="utf-8"
    )
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    (repo / ".github/workflows").mkdir(parents=True)
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "LOCK_HASH_MISSING" in codes


def test_release_contract_rejects_unrecognized_requirement_line(
    tmp_path: Path,
) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "requirements/repoground-runtime.lock.txt").write_text(
        "# Python 3.12\nexample>=1.0\n", encoding="utf-8"
    )
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    (repo / ".github/workflows").mkdir(parents=True)
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "LOCK_REQUIREMENT_UNSUPPORTED" in codes


def test_release_contract_requires_lock_in_path_filters(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    workflows = repo / ".github/workflows"
    workflows.mkdir(parents=True)
    (workflows / "missing-trigger.yml").write_text(
        "on:\n"
        "  pull_request:\n"
        "    paths:\n"
        "      - source.py\n"
        "jobs:\n"
        "  test:\n"
        "    steps:\n"
        "      - run: python -m pip install --require-hashes "
        "-r requirements/repoground-dev.lock.txt\n",
        encoding="utf-8",
    )
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "WORKFLOW_LOCK_TRIGGER_MISSING" in codes


def test_release_contract_rejects_lock_python_mismatch(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    workflows = repo / ".github/workflows"
    workflows.mkdir(parents=True)
    (workflows / "python-mismatch.yml").write_text(
        "jobs:\n"
        "  test:\n"
        "    steps:\n"
        "      - uses: actions/setup-python@deadbeef\n"
        "        with:\n"
        "          python-version: '3.10'\n"
        "      - run: python -m pip install --require-hashes "
        "-r requirements/repoground-dev.lock.txt\n",
        encoding="utf-8",
    )
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "WORKFLOW_LOCK_PYTHON_MISMATCH" in codes



def test_retired_release_contract_paths_match_compatibility_exit() -> None:
    exit_contract = json.loads(
        (ROOT / "docs/contracts/repoground-compatibility-exit.v1.json").read_text(
            encoding="utf-8"
        )
    )
    retired_paths = {
        item["former_path"] for item in exit_contract["retired_contracts"]
    }
    assert retired_paths == set(RETIRED_RELEASE_CONTRACT_PATHS)


@pytest.mark.parametrize(
    "retired_path",
    (
        "merger/repoground/contracts/repobrief-release-candidate.v1.schema.json",
        "merger/repoground/contracts/repobrief-semantic-platforms.v1.schema.json",
    ),
)
def test_retired_repobrief_release_contract_is_rejected(
    tmp_path: Path, retired_path: str
) -> None:
    repo = _repo(tmp_path)
    path = repo / retired_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{}\n", encoding="utf-8")
    _git(repo, "add", retired_path)
    _git(repo, "commit", "-qm", "add retired release contract")

    with pytest.raises(
        ValueError, match="retired RepoBrief release contracts are forbidden"
    ):
        build_release_candidate(repo, tmp_path / "candidate")


@pytest.mark.parametrize("source_bound", (False, True))
@pytest.mark.parametrize("retired_path", RETIRED_RELEASE_CONTRACT_PATHS)
def test_verifier_rejects_archived_retired_repobrief_release_contract(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    retired_path: str,
    source_bound: bool,
) -> None:
    repo = _repo(tmp_path)
    path = repo / retired_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{}\n", encoding="utf-8")
    _git(repo, "add", retired_path)
    _git(repo, "commit", "-qm", "add retired release contract")

    monkeypatch.setattr(
        "scripts.release.build_release_candidate._reject_retired_release_contracts",
        lambda entries: None,
    )
    candidate = tmp_path / "candidate"
    build_release_candidate(repo, candidate)

    kwargs = {"repo": repo} if source_bound else {}
    with pytest.raises(
        ValueError, match="retired RepoBrief release contracts are forbidden"
    ):
        verify_release_candidate(candidate, **kwargs)


@pytest.mark.parametrize("source_bound", (False, True))
@pytest.mark.parametrize("retired_path", RETIRED_RELEASE_CONTRACT_PATHS)
@pytest.mark.parametrize("alias_template", ("./{path}", "{path}/"))
def test_verifier_rejects_noncanonical_alias_for_retired_release_contract(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    retired_path: str,
    alias_template: str,
    source_bound: bool,
) -> None:
    repo = _repo(tmp_path)
    path = repo / retired_path
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("{}\n", encoding="utf-8")
    _git(repo, "add", retired_path)
    _git(repo, "commit", "-qm", "add retired release contract")

    monkeypatch.setattr(
        "scripts.release.build_release_candidate._reject_retired_release_contracts",
        lambda entries: None,
    )
    candidate = tmp_path / "candidate-noncanonical-alias"
    build_release_candidate(repo, candidate)
    _rename_archive_member(
        candidate, retired_path, alias_template.format(path=retired_path)
    )

    kwargs = {"repo": repo} if source_bound else {}
    with pytest.raises(ValueError, match="unsafe archive member"):
        verify_release_candidate(candidate, **kwargs)


@pytest.mark.parametrize("source_bound", (False, True))
def test_verifier_rejects_oversized_archive_member_before_read(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    source_bound: bool,
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-oversized-member"
    build_release_candidate(repo, candidate)
    limit = 1024
    _replace_archive_member_payload(
        candidate,
        "LICENSE",
        b"Apache License\nVersion 2.0\n" + b"0" * limit,
    )
    monkeypatch.setattr(verifier_module, "MAX_ARCHIVE_MEMBER_BYTES", limit)
    kwargs = {"repo": repo} if source_bound else {}
    with pytest.raises(ValueError, match="exceeds byte limit: .*LICENSE"):
        verify_release_candidate(candidate, **kwargs)


def test_verifier_rejects_oversized_manifest_before_json_parsing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-manifest-limit"
    build_release_candidate(repo, candidate)
    manifest_path = next(candidate.glob("*.release.json"))
    monkeypatch.setattr(
        verifier_module, "MAX_MANIFEST_BYTES", manifest_path.stat().st_size - 1
    )
    monkeypatch.setattr(
        verifier_module.json,
        "loads",
        lambda *args, **kwargs: pytest.fail("manifest parsed before size rejection"),
    )
    with pytest.raises(ValueError, match="release manifest exceeds byte limit"):
        verify_release_candidate(candidate)


def test_verifier_rejects_symlinked_manifest_before_read(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-manifest-symlink"
    build_release_candidate(repo, candidate)
    manifest_path = next(candidate.glob("*.release.json"))
    _replace_with_external_symlink(manifest_path, tmp_path)
    with pytest.raises(ValueError, match="release manifest must be a regular non-symlink"):
        verify_release_candidate(candidate)


def test_verifier_binds_sums_to_the_manifest_bytes_that_were_parsed(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-manifest-byte-binding"
    build_release_candidate(repo, candidate)
    original_contract = verifier_module._contract_for_manifest

    def replace_manifest_after_parsing(preview):
        contract = original_contract(preview)
        manifest_path = next(candidate.glob("*.release.json"))
        manifest_path.write_bytes(manifest_path.read_bytes() + b"\n")
        _rewrite_sums(candidate)
        return contract

    monkeypatch.setattr(
        verifier_module,
        "_contract_for_manifest",
        replace_manifest_after_parsing,
    )
    with pytest.raises(ValueError, match="SHA256SUMS does not match"):
        verify_release_candidate(candidate)


def test_verifier_rejects_oversized_sums_before_line_processing(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-sums-limit"
    build_release_candidate(repo, candidate)
    sums_path = candidate / "SHA256SUMS"
    monkeypatch.setattr(
        verifier_module, "MAX_SHA256SUMS_BYTES", sums_path.stat().st_size - 1
    )
    monkeypatch.setattr(
        verifier_module.re,
        "fullmatch",
        lambda *args, **kwargs: pytest.fail("SHA256SUMS processed before size rejection"),
    )
    with pytest.raises(ValueError, match="SHA256SUMS exceeds byte limit"):
        verify_release_candidate(candidate)


def test_verifier_rejects_symlinked_sums_before_read(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-sums-symlink"
    build_release_candidate(repo, candidate)
    _replace_with_external_symlink(candidate / "SHA256SUMS", tmp_path)
    with pytest.raises(ValueError, match="candidate directory may contain regular files only"):
        verify_release_candidate(candidate)


def test_verifier_rejects_compressed_archive_over_limit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-compressed-limit"
    build_release_candidate(repo, candidate)
    archive_path = next(candidate.glob("*.tar.gz"))
    monkeypatch.setattr(
        verifier_module, "MAX_ARCHIVE_BYTES", archive_path.stat().st_size - 1
    )
    monkeypatch.setattr(
        verifier_module,
        "_sha256",
        lambda path: pytest.fail(f"archive hashed before size rejection: {path}"),
    )
    with pytest.raises(ValueError, match="compressed byte limit"):
        verify_release_candidate(candidate)


def test_verifier_rejects_total_uncompressed_bytes_over_limit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-total-limit"
    build_release_candidate(repo, candidate)
    monkeypatch.setattr(verifier_module, "MAX_ARCHIVE_TOTAL_BYTES", 1)
    with pytest.raises(ValueError, match="total uncompressed byte limit"):
        verify_release_candidate(candidate)


def test_verifier_rejects_archive_stream_bytes_over_limit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-stream-limit"
    build_release_candidate(repo, candidate)
    monkeypatch.setattr(verifier_module, "MAX_ARCHIVE_STREAM_BYTES", 1)
    with pytest.raises(ValueError, match="uncompressed stream byte limit"):
        verify_release_candidate(candidate)


def test_source_bound_verifier_batches_blob_content_reads(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-batched-blobs"
    build_release_candidate(repo, candidate)
    original = verifier_module.subprocess.Popen
    batch_calls = 0

    def counted_popen(argv, *args, **kwargs):
        nonlocal batch_calls
        if argv[:3] == ["git", "cat-file", "--batch"]:
            batch_calls += 1
        return original(argv, *args, **kwargs)

    monkeypatch.setattr(verifier_module.subprocess, "Popen", counted_popen)
    assert verify_release_candidate(candidate, repo=repo)["status"] == "pass"
    assert batch_calls == 1


def test_source_bound_verifier_streams_one_blob_at_a_time(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-streamed-blobs"
    build_release_candidate(repo, candidate)
    original = verifier_module._read_repository_blob_batch
    live_blobs = 0
    peak_live_blobs = 0

    def counted_read(process, entry, expected_size):
        nonlocal live_blobs, peak_live_blobs
        live_blobs += 1
        peak_live_blobs = max(peak_live_blobs, live_blobs)
        try:
            return original(process, entry, expected_size)
        finally:
            live_blobs -= 1

    monkeypatch.setattr(verifier_module, "_read_repository_blob_batch", counted_read)
    assert verify_release_candidate(candidate, repo=repo)["status"] == "pass"
    assert peak_live_blobs == 1


def test_source_bound_verifier_checks_blob_size_before_read(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-repository-blob-limit"
    build_release_candidate(repo, candidate)
    monkeypatch.setattr(verifier_module, "MAX_REPOSITORY_BLOB_BYTES", 1)
    original_popen = verifier_module.subprocess.Popen

    def reject_content_batch(argv, *args, **kwargs):
        if argv[:3] == ["git", "cat-file", "--batch"]:
            pytest.fail("repository content batch started before size rejection")
        return original_popen(argv, *args, **kwargs)

    monkeypatch.setattr(verifier_module.subprocess, "Popen", reject_content_batch)
    with pytest.raises(ValueError, match="repository blob exceeds byte limit"):
        verify_release_candidate(candidate, repo=repo)


def test_source_bound_verifier_rejects_total_blob_bytes_before_content_batch(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-repository-total-limit"
    build_release_candidate(repo, candidate)
    monkeypatch.setattr(verifier_module, "MAX_REPOSITORY_TOTAL_BYTES", 1)
    monkeypatch.setattr(
        verifier_module,
        "_open_repository_blob_batch",
        lambda *args, **kwargs: pytest.fail(
            "repository content batch started before total-size rejection"
        ),
    )
    with pytest.raises(ValueError, match="repository blobs exceed total byte limit"):
        verify_release_candidate(candidate, repo=repo)


@pytest.mark.parametrize("source_bound", (False, True))
def test_verifier_materializes_archive_once_per_verification(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    source_bound: bool,
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-single-materialization"
    build_release_candidate(repo, candidate)
    original_materialize = verifier_module._materialized_bounded_tar
    original_tar_open = verifier_module.tarfile.open
    materializations = 0
    tar_opens = 0

    @contextmanager
    def counted_materialization(archive_path: Path):
        nonlocal materializations
        materializations += 1
        with original_materialize(archive_path) as tar_path:
            yield tar_path

    def counted_tar_open(*args, **kwargs):
        nonlocal tar_opens
        tar_opens += 1
        return original_tar_open(*args, **kwargs)

    monkeypatch.setattr(
        verifier_module, "_materialized_bounded_tar", counted_materialization
    )
    monkeypatch.setattr(verifier_module.tarfile, "open", counted_tar_open)
    kwargs = {"repo": repo} if source_bound else {}
    assert verify_release_candidate(candidate, **kwargs)["status"] == "pass"
    assert materializations == 1
    assert tar_opens == 1


def test_verifier_bounds_global_pax_metadata_before_first_member(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-pax-metadata-limit"
    build_release_candidate(repo, candidate)
    _add_global_pax_header(candidate, payload_bytes=4096)
    monkeypatch.setattr(verifier_module, "MAX_ARCHIVE_STREAM_BYTES", 1024)
    monkeypatch.setattr(
        verifier_module,
        "_validate_archive_member",
        lambda *args, **kwargs: pytest.fail(
            "logical archive member yielded before PAX metadata limit"
        ),
    )
    with pytest.raises(ValueError, match="uncompressed stream byte limit"):
        verify_release_candidate(candidate)


def test_verifier_rejects_excessive_compression_ratio(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-ratio-limit"
    build_release_candidate(repo, candidate)
    monkeypatch.setattr(verifier_module, "MAX_ARCHIVE_COMPRESSION_RATIO", 1)
    with pytest.raises(ValueError, match="compression ratio limit"):
        verify_release_candidate(candidate)


def test_verifier_rejects_archive_member_count_over_limit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate-member-count-limit"
    build_release_candidate(repo, candidate)
    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["archive"]["tracked_entry_count"] = 1
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(candidate)
    monkeypatch.setattr(verifier_module, "MAX_ARCHIVE_MEMBERS", 2)
    with pytest.raises(ValueError, match="member count limit"):
        verify_release_candidate(candidate)


def test_legacy_repobrief_release_identity_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate"
    build_release_candidate(repo, candidate)
    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["kind"] = "repobrief.release_candidate"
    manifest["$schema"] = (
        "https://heimgewebe.local/schema/repobrief-release-candidate.v1.schema.json"
    )
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="unsupported or contradictory"):
        verify_release_candidate(candidate)
