from __future__ import annotations

import gzip
import hashlib
import io
import json
import os
import subprocess
import sys
import tarfile
from pathlib import Path

import jsonschema
import pytest

from scripts.release.build_release_candidate import (
    build_release_candidate,
    safe_symlink_target,
)
from scripts.release.check_release_contract import scan
from scripts.release.verify_release_candidate import verify_release_candidate

ROOT = Path(__file__).resolve().parents[3]
SCHEMA = ROOT / "merger/repoground/contracts/repoground-release-candidate.v1.schema.json"
LICENSE_REF = "LicenseRef-RepoGround-All-Rights-Reserved"


def _git(repo: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=repo, text=True).strip()


def _minimal_lock() -> str:
    return (
        "# This file is autogenerated by pip-compile with Python 3.12\n"
        "example==1.0.0 \\\n"
        "    --hash=sha256:" + "a" * 64 + "\n"
    )


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.name", "Release Test")
    _git(repo, "config", "user.email", "release@example.invalid")
    (repo / "RELEASE_VERSION").write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "LICENSE").write_text(
        f"{LICENSE_REF}\nNo permission is granted.\n", encoding="utf-8"
    )
    (repo / "regular.txt").write_text("regular\n", encoding="utf-8")
    executable = repo / "run.sh"
    executable.write_text("#!/bin/sh\necho ok\n", encoding="utf-8")
    executable.chmod(0o755)
    os.symlink("regular.txt", repo / "link.txt")
    locks = repo / "requirements"
    locks.mkdir()
    for name in ("runtime", "dev", "browser", "lock-tools"):
        (locks / f"repoground-{name}.lock.txt").write_text(
            _minimal_lock(), encoding="utf-8"
        )
    semantic_input = locks / "repoground-semantic-linux-x86_64-py312.in"
    semantic_constraints = (
        locks / "repoground-semantic-linux-x86_64-py312.constraints.txt"
    )
    semantic_lock = locks / "repoground-semantic-linux-x86_64-py312.lock.txt"
    semantic_input.write_text("sentence-transformers==5.6.0\n", encoding="utf-8")
    semantic_constraints.write_text("sentence-transformers==5.6.0\n", encoding="utf-8")
    semantic_lock.write_text(_minimal_lock(), encoding="utf-8")
    semantic_contract = repo / "docs/release/repoground-semantic-platforms.v1.json"
    semantic_contract.parent.mkdir(parents=True)
    semantic_contract.write_text(
        json.dumps({"fixture": "semantic-platform-contract"}) + "\n",
        encoding="utf-8",
    )
    semantic_schema = (
        repo
        / "merger/repoground/contracts/repoground-semantic-platforms.v1.schema.json"
    )
    semantic_schema.parent.mkdir(parents=True)
    semantic_schema.write_text(
        json.dumps({"$schema": "http://json-schema.org/draft-07/schema#", "type": "object"})
        + "\n",
        encoding="utf-8",
    )
    (repo / "merger/repoground/requirements-semantic.txt").write_text(
        "sentence-transformers==5.6.0\n", encoding="utf-8"
    )
    release_scripts = repo / "scripts/release"
    release_scripts.mkdir(parents=True, exist_ok=True)
    (release_scripts / "compile_semantic_lock.py").write_text(
        "# fixture\n", encoding="utf-8"
    )
    (release_scripts / "compile_semantic_lock.sh").write_text(
        "#!/bin/sh\n", encoding="utf-8"
    )
    _git(repo, "add", ".")
    _git(repo, "commit", "-qm", "fixture")
    return repo


def _files(path: Path) -> dict[str, bytes]:
    return {item.name: item.read_bytes() for item in sorted(path.iterdir())}



def _rewrite_sums(candidate: Path) -> None:
    manifest = next(candidate.glob("*.release.json"))
    archive = next(candidate.glob("*.tar.gz"))
    lines = [
        f"{hashlib.sha256(archive.read_bytes()).hexdigest()}  {archive.name}",
        f"{hashlib.sha256(manifest.read_bytes()).hexdigest()}  {manifest.name}",
    ]
    (candidate / "SHA256SUMS").write_text(
        "\n".join(sorted(lines)) + "\n", encoding="utf-8"
    )


def _reverse_archive_members(candidate: Path) -> None:
    archive_path = next(candidate.glob("*.tar.gz"))
    members: list[tuple[tarfile.TarInfo, bytes | None]] = []
    with gzip.open(archive_path, "rb") as gz:
        with tarfile.open(fileobj=gz, mode="r:") as tar:
            for member in tar.getmembers():
                handle = tar.extractfile(member) if member.isfile() else None
                members.append((member, handle.read() if handle is not None else None))
    assert members[0][0].isdir()
    reordered = [members[0], *reversed(members[1:])]
    tar_buffer = io.BytesIO()
    with tarfile.open(fileobj=tar_buffer, mode="w", format=tarfile.GNU_FORMAT) as tar:
        for member, payload in reordered:
            tar.addfile(member, io.BytesIO(payload) if payload is not None else None)
    compressed = io.BytesIO()
    with gzip.GzipFile(
        filename="", mode="wb", fileobj=compressed, compresslevel=9, mtime=0
    ) as gz:
        gz.write(tar_buffer.getvalue())
    archive_path.write_bytes(compressed.getvalue())

    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["archive"]["bytes"] = archive_path.stat().st_size
    manifest["archive"]["sha256"] = hashlib.sha256(
        archive_path.read_bytes()
    ).hexdigest()
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(candidate)


def test_candidate_build_is_byte_reproducible_and_source_bound(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    first = tmp_path / "first"
    second = tmp_path / "second"
    result = build_release_candidate(repo, first)
    build_release_candidate(repo, second)
    assert _files(first) == _files(second)
    assert result["distribution_status"] == (
        "blocked_without_separate_written_permission"
    )
    self_report = verify_release_candidate(first)
    source_report = verify_release_candidate(first, repo=repo)
    assert self_report["status"] == "pass"
    assert self_report["source_bound"] is False
    assert source_report["source_bound"] is True


def test_candidate_manifest_validates_against_schema(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest = json.loads(next(out.glob("*.release.json")).read_text())
    schema = json.loads(SCHEMA.read_text())
    jsonschema.Draft7Validator(schema).validate(manifest)


def test_candidate_manifest_binds_optional_semantic_surface(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest = json.loads(next(out.glob("*.release.json")).read_text())
    semantic = manifest["semantic_extension"]
    assert semantic["status"] == "optional_locked"
    assert semantic["default_enabled"] is False
    assert semantic["unsupported_target_policy"] == "fail_closed"
    assert semantic["platform_contract"]["path"] == (
        "docs/release/repoground-semantic-platforms.v1.json"
    )
    target = semantic["targets"][0]
    assert target["id"] == "cpython-312-linux-x86_64"
    assert target["lock"]["path"] == (
        "requirements/repoground-semantic-linux-x86_64-py312.lock.txt"
    )


def test_candidate_semantic_lock_claim_must_match_archive(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest_path = next(out.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["semantic_extension"]["targets"][0]["lock"]["sha256"] = "0" * 64
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _rewrite_sums(out)
    with pytest.raises(ValueError, match="semantic extension SHA-256 mismatch"):
        verify_release_candidate(out)


def test_candidate_tampering_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    result = build_release_candidate(repo, out)
    archive = Path(result["archive"])
    archive.write_bytes(archive.read_bytes() + b"tampered")
    with pytest.raises(ValueError, match="SHA256SUMS"):
        verify_release_candidate(out)




def test_noncanonical_archive_member_order_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    _reverse_archive_members(out)
    with pytest.raises(ValueError, match="archive member order is not canonical"):
        verify_release_candidate(out, repo=repo)


def test_manifest_lock_claim_must_match_archived_lock(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest_path = next(out.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["dependency_locks"][0]["sha256"] = "0" * 64
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    _rewrite_sums(out)
    with pytest.raises(ValueError, match="dependency lock SHA-256 mismatch"):
        verify_release_candidate(out)

def test_dirty_repository_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    (repo / "regular.txt").write_text("dirty\n", encoding="utf-8")
    with pytest.raises(ValueError, match="clean working tree"):
        build_release_candidate(repo, tmp_path / "candidate")



def test_nonempty_output_directory_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    out.mkdir()
    (out / "stale.txt").write_text("stale\n", encoding="utf-8")
    with pytest.raises(ValueError, match="must be empty"):
        build_release_candidate(repo, out)


def test_extra_candidate_file_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    (out / "unexpected.txt").write_text("unexpected\n", encoding="utf-8")
    with pytest.raises(ValueError, match="file set mismatch"):
        verify_release_candidate(out)


def test_symlink_target_must_remain_inside_archive(tmp_path: Path) -> None:
    assert safe_symlink_target("nested/link", "../regular.txt")
    assert not safe_symlink_target("link", "../outside.txt")
    assert not safe_symlink_target("nested/link", "/etc/passwd")

    repo = _repo(tmp_path)
    os.symlink("../../outside.txt", repo / "nested-escape")
    _git(repo, "add", "nested-escape")
    _git(repo, "commit", "-qm", "unsafe symlink")
    with pytest.raises(ValueError, match="unsafe symlink target"):
        build_release_candidate(repo, tmp_path / "candidate")


def test_repository_release_contract_is_consistent() -> None:
    report = scan(ROOT)
    assert report["status"] == "pass", report["findings"]


def test_release_contract_gate_runs_without_site_packages() -> None:
    result = subprocess.run(
        [sys.executable, "-S", "scripts/release/check_release_contract.py"],
        cwd=ROOT,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )
    assert result.returncode == 0, result.stderr or result.stdout
    assert json.loads(result.stdout)["status"] == "pass"


def test_release_contract_rejects_unhashed_lock(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    # Supply the remaining policy files so the lock finding is isolated.
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "requirements/repoground-runtime.lock.txt").write_text(
        "# Python 3.12\nexample==1.0.0 \\\n", encoding="utf-8"
    )
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    (repo / ".github/workflows").mkdir(parents=True)
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "LOCK_HASH_MISSING" in codes


def test_release_contract_rejects_unrecognized_requirement_line(
    tmp_path: Path,
) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "requirements/repoground-runtime.lock.txt").write_text(
        "# Python 3.12\nexample>=1.0\n", encoding="utf-8"
    )
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    (repo / ".github/workflows").mkdir(parents=True)
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "LOCK_REQUIREMENT_UNSUPPORTED" in codes


def test_release_contract_requires_lock_in_path_filters(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    workflows = repo / ".github/workflows"
    workflows.mkdir(parents=True)
    (workflows / "missing-trigger.yml").write_text(
        "on:\n"
        "  pull_request:\n"
        "    paths:\n"
        "      - source.py\n"
        "jobs:\n"
        "  test:\n"
        "    steps:\n"
        "      - run: python -m pip install --require-hashes "
        "-r requirements/repoground-dev.lock.txt\n",
        encoding="utf-8",
    )
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "WORKFLOW_LOCK_TRIGGER_MISSING" in codes


def test_release_contract_rejects_lock_python_mismatch(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repoground-runtime.in",
        "requirements/repoground-dev.in",
        "requirements/repoground-browser.in",
        "requirements/repoground-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    workflows = repo / ".github/workflows"
    workflows.mkdir(parents=True)
    (workflows / "python-mismatch.yml").write_text(
        "jobs:\n"
        "  test:\n"
        "    steps:\n"
        "      - uses: actions/setup-python@deadbeef\n"
        "        with:\n"
        "          python-version: '3.10'\n"
        "      - run: python -m pip install --require-hashes "
        "-r requirements/repoground-dev.lock.txt\n",
        encoding="utf-8",
    )
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "WORKFLOW_LOCK_PYTHON_MISMATCH" in codes



def test_legacy_repobrief_release_identity_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    candidate = tmp_path / "candidate"
    build_release_candidate(repo, candidate)
    manifest_path = next(candidate.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["kind"] = "repobrief.release_candidate"
    manifest["$schema"] = (
        "https://heimgewebe.local/schema/repobrief-release-candidate.v1.schema.json"
    )
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    with pytest.raises(ValueError, match="unsupported or contradictory"):
        verify_release_candidate(candidate)
