from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
REPOBRIEF_DOC = REPO_ROOT / "docs/architecture/repobrief.md"
NAMING_DOC = REPO_ROOT / "docs/architecture/naming.md"


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def test_repobrief_doc_defines_public_name_without_package_rename() -> None:
    text = _read(REPOBRIEF_DOC)

    assert "RepoBrief is the public system name" in text
    assert "historical repository and Python package name remains `lenskit`" in text
    assert "no package rename" in text
    assert "no schema kind rename" in text
    assert "no import-path migration" in text


def test_repobrief_doc_preserves_authority_and_negative_semantics() -> None:
    text = _read(REPOBRIEF_DOC)

    assert "Canonical Brief Source is the sole content authority" in text
    assert "Brief Sidecars are navigation, diagnostic, evidence-index, or cache surfaces" in text
    assert "A Brief Bundle is a snapshot at generation time" in text

    for boundary in (
        "truth",
        "correctness",
        "completeness",
        "runtime_behavior",
        "test_sufficiency",
        "regression_absence",
        "repo_understood",
        "claims_true",
        "forensic_ready",
    ):
        assert f"`{boundary}`" in text


def test_repobrief_doc_separates_create_and_read_paths() -> None:
    text = _read(REPOBRIEF_DOC)

    assert "create operations" in text
    assert "read operations" in text
    assert "must not write or refresh" in text
    assert "must not be silently regenerated by a read path" in text


def test_naming_doc_maps_legacy_terms_to_repobrief_terms() -> None:
    text = _read(NAMING_DOC)

    for expected in (
        "RepoBrief",
        "Brief Snapshot",
        "Brief Bundle",
        "Canonical Brief Source",
        "Brief Sidecars",
        "Agent Brief / Reading Pack",
        "Brief Health",
        "Brief Surface",
    ):
        assert expected in text


def test_naming_doc_keeps_phase_one_compatibility_boundary() -> None:
    text = _read(NAMING_DOC)

    for boundary in (
        "rename `merger.lenskit` imports",
        "rename existing JSON `kind` values",
        "remove existing CLI commands",
        "invalidate existing generated bundles",
    ):
        assert boundary in text

    assert "No later path is selected by this document." in text
