from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path

import jsonschema
import pytest

from scripts.release.build_release_candidate import (
    build_release_candidate,
    safe_symlink_target,
)
from scripts.release.check_release_contract import scan
from scripts.release.verify_release_candidate import verify_release_candidate

ROOT = Path(__file__).resolve().parents[3]
SCHEMA = ROOT / "merger/lenskit/contracts/repobrief-release-candidate.v1.schema.json"
LICENSE_REF = "LicenseRef-RepoBrief-All-Rights-Reserved"


def _git(repo: Path, *args: str) -> str:
    return subprocess.check_output(["git", *args], cwd=repo, text=True).strip()


def _minimal_lock() -> str:
    return (
        "# This file is autogenerated by pip-compile with Python 3.12\n"
        "example==1.0.0 \\\n"
        "    --hash=sha256:" + "a" * 64 + "\n"
    )


def _repo(tmp_path: Path) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir()
    _git(repo, "init", "-q")
    _git(repo, "config", "user.name", "Release Test")
    _git(repo, "config", "user.email", "release@example.invalid")
    (repo / "RELEASE_VERSION").write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "LICENSE").write_text(
        f"{LICENSE_REF}\nNo permission is granted.\n", encoding="utf-8"
    )
    (repo / "regular.txt").write_text("regular\n", encoding="utf-8")
    executable = repo / "run.sh"
    executable.write_text("#!/bin/sh\necho ok\n", encoding="utf-8")
    executable.chmod(0o755)
    os.symlink("regular.txt", repo / "link.txt")
    locks = repo / "requirements"
    locks.mkdir()
    for name in ("runtime", "dev", "browser", "lock-tools"):
        (locks / f"repobrief-{name}.lock.txt").write_text(
            _minimal_lock(), encoding="utf-8"
        )
    _git(repo, "add", ".")
    _git(repo, "commit", "-qm", "fixture")
    return repo


def _files(path: Path) -> dict[str, bytes]:
    return {item.name: item.read_bytes() for item in sorted(path.iterdir())}



def _rewrite_sums(candidate: Path) -> None:
    manifest = next(candidate.glob("*.release.json"))
    archive = next(candidate.glob("*.tar.gz"))
    lines = [
        f"{hashlib.sha256(archive.read_bytes()).hexdigest()}  {archive.name}",
        f"{hashlib.sha256(manifest.read_bytes()).hexdigest()}  {manifest.name}",
    ]
    (candidate / "SHA256SUMS").write_text(
        "\n".join(sorted(lines)) + "\n", encoding="utf-8"
    )

def test_candidate_build_is_byte_reproducible_and_source_bound(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    first = tmp_path / "first"
    second = tmp_path / "second"
    result = build_release_candidate(repo, first)
    build_release_candidate(repo, second)
    assert _files(first) == _files(second)
    assert result["distribution_status"] == (
        "blocked_without_separate_written_permission"
    )
    self_report = verify_release_candidate(first)
    source_report = verify_release_candidate(first, repo=repo)
    assert self_report["status"] == "pass"
    assert self_report["source_bound"] is False
    assert source_report["source_bound"] is True


def test_candidate_manifest_validates_against_schema(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest = json.loads(next(out.glob("*.release.json")).read_text())
    schema = json.loads(SCHEMA.read_text())
    jsonschema.Draft7Validator(schema).validate(manifest)


def test_candidate_tampering_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    result = build_release_candidate(repo, out)
    archive = Path(result["archive"])
    archive.write_bytes(archive.read_bytes() + b"tampered")
    with pytest.raises(ValueError, match="SHA256SUMS"):
        verify_release_candidate(out)



def test_manifest_lock_claim_must_match_archived_lock(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    manifest_path = next(out.glob("*.release.json"))
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    manifest["dependency_locks"][0]["sha256"] = "0" * 64
    manifest_path.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    _rewrite_sums(out)
    with pytest.raises(ValueError, match="dependency lock SHA-256 mismatch"):
        verify_release_candidate(out)

def test_dirty_repository_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    (repo / "regular.txt").write_text("dirty\n", encoding="utf-8")
    with pytest.raises(ValueError, match="clean working tree"):
        build_release_candidate(repo, tmp_path / "candidate")



def test_nonempty_output_directory_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    out.mkdir()
    (out / "stale.txt").write_text("stale\n", encoding="utf-8")
    with pytest.raises(ValueError, match="must be empty"):
        build_release_candidate(repo, out)


def test_extra_candidate_file_is_rejected(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    out = tmp_path / "candidate"
    build_release_candidate(repo, out)
    (out / "unexpected.txt").write_text("unexpected\n", encoding="utf-8")
    with pytest.raises(ValueError, match="file set mismatch"):
        verify_release_candidate(out)


def test_symlink_target_must_remain_inside_archive(tmp_path: Path) -> None:
    assert safe_symlink_target("nested/link", "../regular.txt")
    assert not safe_symlink_target("link", "../outside.txt")
    assert not safe_symlink_target("nested/link", "/etc/passwd")

    repo = _repo(tmp_path)
    os.symlink("../../outside.txt", repo / "nested-escape")
    _git(repo, "add", "nested-escape")
    _git(repo, "commit", "-qm", "unsafe symlink")
    with pytest.raises(ValueError, match="unsafe symlink target"):
        build_release_candidate(repo, tmp_path / "candidate")


def test_repository_release_contract_is_consistent() -> None:
    report = scan(ROOT)
    assert report["status"] == "pass", report["findings"]


def test_release_contract_rejects_unhashed_lock(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    # Supply the remaining policy files so the lock finding is isolated.
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repobrief-runtime.in",
        "requirements/repobrief-dev.in",
        "requirements/repobrief-browser.in",
        "requirements/repobrief-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "requirements/repobrief-runtime.lock.txt").write_text(
        "# Python 3.12\nexample==1.0.0 \\\n", encoding="utf-8"
    )
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    (repo / ".github/workflows").mkdir(parents=True)
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "LOCK_HASH_MISSING" in codes


def test_release_contract_rejects_unrecognized_requirement_line(
    tmp_path: Path,
) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repobrief-runtime.in",
        "requirements/repobrief-dev.in",
        "requirements/repobrief-browser.in",
        "requirements/repobrief-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "requirements/repobrief-runtime.lock.txt").write_text(
        "# Python 3.12\nexample>=1.0\n", encoding="utf-8"
    )
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    (repo / ".github/workflows").mkdir(parents=True)
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "LOCK_REQUIREMENT_UNSUPPORTED" in codes


def test_release_contract_requires_lock_in_path_filters(tmp_path: Path) -> None:
    repo = _repo(tmp_path)
    for relative in (
        "CHANGELOG.md",
        "docs/release/licensing.md",
        "docs/release/release-policy.md",
        "docs/release/upgrade-rollback.md",
        "scripts/release/build_release_candidate.py",
        "scripts/release/verify_release_candidate.py",
        "scripts/release/compile_dependency_locks.sh",
        "requirements/repobrief-runtime.in",
        "requirements/repobrief-dev.in",
        "requirements/repobrief-browser.in",
        "requirements/repobrief-lock-tools.in",
    ):
        path = repo / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("2.4.0-rc.1\n", encoding="utf-8")
    (repo / "CHANGELOG.md").write_text("## [2.4.0-rc.1]\n", encoding="utf-8")
    (repo / "docs/tasks").mkdir(parents=True)
    (repo / "docs/tasks/index.json").write_text(
        json.dumps(
            {
                "tasks": [
                    {"id": "TASK-LENSKIT-SEMANTIC-LOCK-001"},
                    {"id": "TASK-REPOBRIEF-PUBLIC-LICENSE-DECISION-001"},
                ]
            }
        ),
        encoding="utf-8",
    )
    workflows = repo / ".github/workflows"
    workflows.mkdir(parents=True)
    (workflows / "missing-trigger.yml").write_text(
        "on:\n"
        "  pull_request:\n"
        "    paths:\n"
        "      - source.py\n"
        "jobs:\n"
        "  test:\n"
        "    steps:\n"
        "      - run: python -m pip install --require-hashes "
        "-r requirements/repobrief-dev.lock.txt\n",
        encoding="utf-8",
    )
    report = scan(repo)
    codes = {item["code"] for item in report["findings"]}
    assert "WORKFLOW_LOCK_TRIGGER_MISSING" in codes
