---
name: PR Heimgewebe commands

"on":
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  dispatch:
    if: github.event.issue.pull_request != null && github.event.comment.user.type != 'Bot'
    uses: heimgewebe/metarepo/.github/workflows/heimgewebe-command-dispatch.yml@fe6950616b2d06343e284a56a8944e0a36f1f972  # metarepo PR #646 merge 2026-07-12
    secrets:
      HEIMGEWEBE_APP_ID: ${{ secrets.HEIMGEWEBE_APP_ID }}
      HEIMGEWEBE_APP_PRIVATE_KEY: ${{ secrets.HEIMGEWEBE_APP_PRIVATE_KEY }}
