#!/usr/bin/env bash
# Forensic Preflight CI Canary
#
# Controlled canary for `governance forensic-preflight`. It builds a small,
# hermetic, registry-bearing fixture bundle through the standard merge pipeline,
# persists post_emit_health, runs the forensic preflight CLI, persists the
# machine-readable JSON report and asserts a strict PASS.
#
# A PASS means the *formal* forensic_strict prerequisites are present (manifest,
# canonical/chunk/citation/claim-map hashes, claim-map schema, post-emit health,
# range-strict evidence, explicit redaction policy). It is NOT a claim-truth
# verdict, NOT a license for an agent to answer without citations, and it does
# NOT promote forensic_strict to a global blocking policy. The full blocking
# promotion remains a follow-up after several stable canary runs.
#
# Scope guard: this canary changes no core bundle-emission, claim-map or surface
# logic. It only exercises the existing CLI against a controlled fixture.
#
# Env:
#   OUT          working directory (default: <repo>/.tmp/forensic-preflight-ci-canary)
#   ARTIFACT_DIR machine-readable output dir (default: $OUT/artifacts)
#   KEEP         set to 1 to keep the scratch working dir for manual forensics
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${repo_root}"

OUT="${OUT:-${repo_root}/.tmp/forensic-preflight-ci-canary}"
ARTIFACT_DIR="${ARTIFACT_DIR:-${OUT}/artifacts}"
KEEP="${KEEP:-0}"
WORKDIR="${OUT}/work"

rm -rf -- "${WORKDIR}"
mkdir -p "${OUT}" "${ARTIFACT_DIR}" "${WORKDIR}"

cleanup() {
  # Keep the artifact JSON (ARTIFACT_DIR) for CI upload; only drop the scratch
  # bundle working tree unless KEEP=1 requests it for manual forensics.
  if [[ "${KEEP}" != "1" && -n "${WORKDIR:-}" && -d "${WORKDIR}" ]]; then
    rm -rf -- "${WORKDIR}"
  fi
}
trap cleanup EXIT

ARTIFACT_JSON="${ARTIFACT_DIR}/forensic-preflight-canary.json"
MANIFEST_REF="${WORKDIR}/manifest_path.txt"

echo "== forensic preflight ci canary =="
echo "repo_root=${repo_root}"
echo "OUT=${OUT}"
echo "ARTIFACT_DIR=${ARTIFACT_DIR}"
echo "WORKDIR=${WORKDIR}"

# 1. Build a hermetic, registry-bearing fixture bundle through the standard
#    merge pipeline and persist post_emit_health. The fixture ships its own
#    docs/doc-freshness-registry.yml so claim_evidence_map_json is produced
#    deterministically: single-repo bundles derive the claim map from the
#    scanned repo's registry (merge.py), and without one the map is correctly
#    absent and preflight would block. max_bytes=100_000 yields the strict
#    navigation artifacts (chunk_index + citation_map) the preflight requires.
python3 - "${WORKDIR}" "${MANIFEST_REF}" <<'PY'
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

from merger.lenskit.core.merge import ExtrasConfig, scan_repo, write_reports_v2
from merger.lenskit.core.post_emit_health import (
    derive_post_health_path,
    write_post_emit_health,
)

workdir = Path(sys.argv[1]).resolve()
manifest_ref = Path(sys.argv[2])

REQUIRED_ROLES = {
    "canonical_md",
    "chunk_index_jsonl",
    "citation_map_jsonl",
    "claim_evidence_map_json",
}

# Minimal, schema-valid doc-freshness registry (doc-freshness-registry v1.0).
# produce_claim_evidence_map() validates this against
# merger/lenskit/contracts/doc-freshness-registry.v1.schema.json. Embedding it
# keeps the canary deterministic and independent of the repo's own registry.
REGISTRY_YAML = """\
kind: lenskit.doc_freshness_registry
version: "1.0"
authority: diagnostic_signal
risk_class: diagnostic
does_not_prove:
  - "a green verify does not prove docs are complete or correct, only that no tracked claim contradicts its declared evidence"
entries:
  - id: canary-fixture-app-answer
    doc: docs/usage.md
    locator: "section 'Usage'"
    claim: "answer() returns a deterministic result"
    status: done
    normative: false
    owner: forensic-canary
    last_verified: "2026-06-03"
    evidence:
      - kind: symbol
        target: "src/app.py::answer"
      - kind: file
        target: "docs/usage.md"
"""

fixture = workdir / "fixture-repo"
(fixture / "src").mkdir(parents=True, exist_ok=True)
(fixture / "docs").mkdir(parents=True, exist_ok=True)
(fixture / "README.md").write_text(
    "# Forensic Canary Fixture\n\n"
    "Deterministic source content generated by the forensic preflight CI canary.\n",
    encoding="utf-8",
)
(fixture / "src" / "app.py").write_text(
    "def answer() -> int:\n    return 42\n",
    encoding="utf-8",
)
(fixture / "docs" / "usage.md").write_text(
    "# Usage\n\nCall `answer()` when the fixture needs deterministic source content.\n",
    encoding="utf-8",
)
(fixture / "docs" / "doc-freshness-registry.yml").write_text(
    REGISTRY_YAML, encoding="utf-8"
)

case_root = workdir / "case"
case_repo = case_root / fixture.name
case_merges = case_root / "merges"
case_root.mkdir(parents=True, exist_ok=True)
shutil.copytree(fixture, case_repo)
case_merges.mkdir(exist_ok=True)

summary = scan_repo(case_repo, max_bytes=100_000, include_hidden=True)
artifacts = write_reports_v2(
    case_merges,
    case_root,
    [summary],
    "forensic-canary",
    "gesamt",
    100_000,
    False,
    split_size=0,
    extras=ExtrasConfig(augment_sidecar=True, json_sidecar=True),
    output_mode="dual",
    redact_secrets=False,
    generator_info={
        "name": "lenskit-forensic-canary",
        "version": "ci-canary",
        "config_sha256": "7" * 64,
    },
)
if artifacts.bundle_manifest is None:
    raise SystemExit("FAILED: canary bundle generation did not return a bundle manifest")

manifest = artifacts.bundle_manifest.resolve()
doc = json.loads(manifest.read_text(encoding="utf-8"))
roles = {a.get("role") for a in doc.get("artifacts", []) if isinstance(a, dict)}
missing = sorted(REQUIRED_ROLES - roles)
if missing:
    raise SystemExit(f"FAILED: canary bundle missing required roles: {missing}")

write_post_emit_health(str(manifest))
post_path = derive_post_health_path(manifest)
if not post_path.is_file():
    raise SystemExit("FAILED: post_emit_health was not persisted next to the manifest")

manifest_ref.write_text(str(manifest) + "\n", encoding="utf-8")
print(f"canary_manifest={manifest}")
print(f"canary_roles={sorted(roles)}")
PY

MANIFEST="$(cat "${MANIFEST_REF}")"
if [[ -z "${MANIFEST}" || ! -f "${MANIFEST}" ]]; then
  echo "FAILED: no bundle manifest produced" >&2
  exit 2
fi
echo "MANIFEST=${MANIFEST}"

# 2. Run the forensic preflight CLI. Capture the JSON report even when the CLI
#    exits non-zero (blocked/fail still emit a machine-readable report) so the
#    artifact is always available for upload and the diagnosis stays precise.
set +e
python3 -m merger.lenskit.cli.main governance forensic-preflight \
  --manifest "${MANIFEST}" \
  --json > "${ARTIFACT_JSON}"
cli_exit=$?
set -e
echo "forensic-preflight CLI exit: ${cli_exit}"
echo "artifact: ${ARTIFACT_JSON}"

# 3. Strict canary gate: the positive fixture MUST reach status=pass. A merely
#    environment-blocked result (e.g. jsonschema not installed) is a canary
#    failure, not a silent pass.
python3 - "${ARTIFACT_JSON}" "${cli_exit}" <<'PY'
import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
cli_exit = sys.argv[2]

raw = path.read_text(encoding="utf-8") if path.is_file() else ""
if not raw.strip():
    raise SystemExit(
        f"FAILED: forensic preflight emitted no JSON report (CLI exit {cli_exit}); "
        "the manifest may be unreadable or the CLI errored before emitting."
    )

data = json.loads(raw)
status = data.get("status") or data.get("verdict")
print(f"forensic_preflight_status={status!r}")

non_pass = [
    (c.get("name"), c.get("status"))
    for c in data.get("checks", [])
    if isinstance(c, dict) and c.get("status") != "pass"
]
if non_pass:
    print("non-pass checks:")
    for name, st in non_pass:
        print(f"  {st}: {name}")

if status != "pass":
    raise SystemExit(
        f"FAILED: forensic preflight canary expected status=pass, got {status!r}. "
        "PASS means the formal forensic_strict prerequisites are present; this "
        "canary does not assert claim truth."
    )

print("OK: forensic preflight canary PASS (formal prerequisites present; not a truth verdict)")
PY

echo "== forensic preflight ci canary: PASS =="
